// Code generated by internal/tools/genversions; DO NOT EDIT.

package datafusion

const (
	// DataFusionVersion is the exact Rust datafusion crate version pinned by this release.
	DataFusionVersion = "53.1.0"

	// DataFusionVersionEncoded is used in Go module tags: v<major>.<encoded-datafusion-version>.<patch>.
	DataFusionVersionEncoded = "530100"

	// DataFusionGoMajor is the major component of datafusion-go release tags.
	DataFusionGoMajor = 0

	// DataFusionGoPatch is the patch component of datafusion-go release tags.
	DataFusionGoPatch = 1

	// DataFusionGoVersion is the full datafusion-go module version without the leading v.
	DataFusionGoVersion = "0.530100.1"
)
